from .base_policies import policy_cli
from .first_player_policy import first_player_naive_policy as first_player_policy
from .second_player_policy import second_player_naive_policy as second_player_policy
